name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npx vsce package
      - uses: actions/upload-artifact@v2
        with:
          name: VSIX
          path: "*.vsix"
      - name: Publish
        if: success() && startsWith( github.ref, 'refs/tags/v')
        run: "npx vsce publish --packagePath *.vsix"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
